import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from '@/components/header';
import Providers from '@/features/provider';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* Container */}
        <Providers>
            <Header />
              <div className="max-w-[1300px] m-auto pl-4 pr-4 text-main_fourth">
                  {children}
              </div>
        </Providers>
      </body>
    </html>
  );
}
